Add policy checks for packages before publishing
We want to ensure that when we publish a package, none of the
dependencies are pre-release dependencies (which we, for better or
worse, end up using often during cross cutting development across our
many repositories).

This change adds a new script, `check-package-dependencies` that will
run validation logic against the package.json we are about to publish
and use its exit code to communicate if the package should be
published or not.

Our shared publishing script uses this a pre-check before actually
doing the publish.

diff --git a/ci/publish-tfgen-package b/ci/publish-tfgen-package
--- a/ci/publish-tfgen-package
+++ b/ci/publish-tfgen-package
@@ -13,6 +13,12 @@ fi
 SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 SOURCE_ROOT="$1"
 
+# Before we publish, we run some validation checks over the package
+if ! "${SCRIPT_ROOT}"/check-package-dependencies "${SOURCE_ROOT}/sdk/nodejs/bin/package.json"; then
+    >&2 echo "checking package dependencies failed, refusing to publish"
+    exit 1
+fi
+
 if [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
     # Publish the NPM package.
     echo "Publishing NPM package to NPMjs.com:"
